### ISSUE TITLE
打包过后的托盘图标丢失

### ISSUE THREAD

**Issue by jahnli** [Innei/electron-typescript-starter#1]
![image](https://user-images.githubusercontent.com/20943608/87910432-9911a200-ca9c-11ea-9b93-b5f65a6aea95.png)

大佬有没有遇到过，electron-builder后，程序运行正常但是任务栏图标丢失 是什么问题 ？

**Comment by Innei** [comment]
__static is made available to provide you a path to your static/ folder not public/
